# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan's Tech Blog Test
email: heintzelman@gmail.com
description: "This is a test of my first use of Jekyll framework following the Lynda.com tutorial by James Williamson."
baseurl: "/tutorial_jekyll_blog"
url: "http://Heintzdm.github.io/tutorial_jekyll_blog"
tagline: "A basic guide to Jekyll"


# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
gems: [jekyll-paginate]
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
